name: Greetings for All

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened,closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            @${{ github.actor }} Thanks for opening the Issues, This Will definitely Imporove our Project Please read [Contrinutions Guidlines](https://github.com/Sukriti-sood/Unsplash/edit/main/.github/workflows/greetings.yml).
    - name: Create comment for PR
      if: github.event_name == 'pull_request_target'&& github.event.action == 'opened'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.actor }} Thank you for Opening  pull request. We will soon be getting back to you. Your patience will be greatly appreciated!Thanks! 🥳.
    - name: Create comment for Merging PR
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.event.pull_request.user.login }} your PR got merged.    

