name: Greetings

on:
  issues:
    types: [opened,closed]
  pull_request:
    types: [opened]
jobs:

  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            @${{ github.actor }} You just created a issue.
    - name: Create comment for Merging PR
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: |
            @${{ github.actor }} your PR got merged.            
    - name: Create comment for Opening PR
      if: github.event_name == 'pull_request' && github.event.action == 'opened' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.actor }} you just opende a PR.
